build_site:
  stage: build
  script:
    - docker run --rm -v $(pwd):/app -w /app node:20 bash -c "rm -rf node_modules && npm install && npm run build"
  artifacts:
    paths:
      - public
  only:
    - main
