image: node:latest

cache:
  paths:
    - .cache/
    - node_modules/
    - public/

pages:
  script:
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  only:
    - main