build_site:
  stage: build
  script:
    - docker run --rm -v $(pwd):/app -w /app node:14 npm install
    - docker run --rm -v $(pwd):/app -w /app node:14 npm run build
  artifacts:
    paths:
      - public
  only:
    - main
