build_site:
  stage: build
  script:
    - docker run -v $(pwd):/app -w /app node:18 npm install
    - docker run -v $(pwd):/app -w /app node:18 npm run build
  artifacts:
    paths:
      - public
  only:
    - main
